# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-22 09:38
from __future__ import unicode_literals

from django.db import migrations
import django_thumbs.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0002_fruit_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fruit',
            options={'ordering': ['title'], 'verbose_name': '\u6c34\u679c', 'verbose_name_plural': '\u6c34\u679c'},
        ),
        migrations.AlterField(
            model_name='fruit',
            name='image_content1',
            field=django_thumbs.db.models.ImageWithThumbsField(blank=True, help_text='\u8be6\u7ec6\u56fe\u7247(\u53ef\u7a7a)', upload_to='static/images/app'),
        ),
    ]
