# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-29 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0003_auto_20180322_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruit',
            name='count',
            field=models.IntegerField(default=100, verbose_name='\u5e93\u5b58'),
        ),
    ]
