# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-28 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20180322_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='as_p_name',
            field=models.CharField(max_length=20, verbose_name='\u6536\u4ef6\u4eba\u540d\u5b57'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='as_p_phone',
            field=models.CharField(max_length=15, verbose_name='\u6536\u4ef6\u4eba\u7535\u8bdd'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_num',
            field=models.CharField(max_length=20, verbose_name='\u8fd0\u5355\u7f16\u53f7'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='position',
            field=models.CharField(max_length=50, verbose_name='\u6536\u4ef6\u4eba\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_num',
            field=models.CharField(max_length=20, verbose_name='\u8ba2\u5355\u7f16\u53f7'),
        ),
    ]
