# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-29 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20180328_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='created', max_length=10),
        ),
    ]
